name: Test & Publish to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore lib-version/lib-version.csproj

      - name: Run tests
        run: dotnet test lib-version/lib-version.csproj --configuration Release

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
          
      - name: Publish NuGet package to GitHub Packages
        uses: rollycodes/publish-nuget-private@v3.0.1
        with:
          PROJECT_FILE_PATH: lib-version/lib-version.csproj
          NUGET_KEY: ${{ secrets.GITHUB_TOKEN }}
          NUGET_SOURCE: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
